kind: Deployment
apiVersion: apps/v1
metadata:
  name: hls-scte35-manipulator-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hls-scte35-manipulator-server
  template:
    metadata:
      labels:
        app: hls-scte35-manipulator-server
    spec:
      containers:
      - name: hls-scte35-manipulator-server
        image: lalalaciccio/hls-scte35-manipulator-server:latest
        ports:
          - containerPort: 4999
            protocol: TCP        
        command: ["hls-scte35-manipulator-server"]
        args: ["--origin-base-url", "nginx:5000", "--profile", "profiles/profile-descriptor-ads-filter.json", "--host", "0.0.0.0", "--port", "4999"]